// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB52YuBiKVfTKxH6qkURZAPXYdfzGJu68c',
    appId: '1:505976113972:android:1577c785f2d825b299b361',
    messagingSenderId: '505976113972',
    projectId: 'ecommerce-d178d',
    storageBucket: 'ecommerce-d178d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8Uyvr_x6U8C8QdMSFUO4JoEHfRR3_x50',
    appId: '1:505976113972:ios:78164ffcb2d5bd8499b361',
    messagingSenderId: '505976113972',
    projectId: 'ecommerce-d178d',
    storageBucket: 'ecommerce-d178d.appspot.com',
    iosClientId: '505976113972-doo70k9tg0b0qe55fjt0nda8ptl3bnol.apps.googleusercontent.com',
    iosBundleId: 'com.spydastack.ecommerce',
  );
}
